Repository PaddleHQ/paddle-node-sdk, pull requests merged in 2024-11, with the labels that each got.

#67 Saved payment methods 💳
  CHANGELOG.md
  package.json
  src/__tests__/mocks/notifications/payment-method-deleted.mock.ts
  src/__tests__/mocks/notifications/payment-method-saved.mock.ts
  src/__tests__/mocks/resources/customers.mock.ts
  src/__tests__/mocks/resources/payment-methods.mock.ts
  src/__tests__/notifications/notifications-parser.test.ts
  src/__tests__/resources/customers.test.ts
  src/__tests__/resources/payment-methods.test.ts
  src/entities/customer/auth-token.ts
  src/entities/customer/index.ts
  src/entities/index.ts
  src/entities/payment-method/index.ts
  src/entities/payment-method/payment-method-collection.ts
  src/entities/payment-method/payment-method.ts
  src/entities/shared/index.ts
  src/entities/shared/paypal.ts
  src/enums/index.ts
  src/enums/payment-method/deletion-reason.ts
  src/enums/payment-method/index.ts
  src/enums/payment-method/origin.ts
  src/enums/payment-method/type.ts
  src/notifications/entities/index.ts
  src/notifications/entities/payment-method/index.ts
  src/notifications/entities/payment-method/payment-method-deleted-notification.ts
  src/notifications/entities/payment-method/payment-method-notification.ts
  src/notifications/events/index.ts
  src/notifications/events/payment-method/index.ts
  src/notifications/events/payment-method/payment-method-deleted-event.ts
  src/notifications/events/payment-method/payment-method-saved-event.ts
  src/notifications/helpers/types.ts
  src/notifications/helpers/webhooks.ts
  src/notifications/types/index.ts
  src/notifications/types/payment-method/index.ts
  src/notifications/types/payment-method/payment-method-deleted-notification-response.ts
  src/notifications/types/payment-method/payment-method-notification-response.ts
  src/paddle.ts
  src/resources/customers/index.ts
  src/resources/index.ts
  src/resources/payment-methods/index.ts
  src/resources/payment-methods/operations/index.ts
  src/resources/payment-methods/operations/list-customer-payment-method-query-parameters.ts
  src/types/customer/auth-token-response.ts
  src/types/customer/index.ts
  src/types/events/events-response.ts
  src/types/index.ts
  src/types/payment-method/index.ts
  src/types/payment-method/payment-method.ts
  src/types/shared/index.ts
  src/types/shared/paypal.ts
Labels: release:minor

#66 remove lodash
  package.json
  src/internal/api/case-helpers.ts
  yarn.lock
Labels: norelease

#72 chore: bump version to v2 stable
  CHANGELOG.md
  package.json
Labels: release:major

#74 Customer Portal Sessions
  CHANGELOG.md
  package.json
  src/__tests__/mocks/resources/customer-portal-sessions.mock.ts
  src/__tests__/resources/customer-portal-sessions.test.ts
  src/entities/customer-portal-session/customer-portal-session.ts
  src/entities/customer-portal-session/customer-portal-subscription-url.ts
  src/entities/customer-portal-session/general.ts
  src/entities/customer-portal-session/index.ts
  src/entities/customer-portal-session/urls.ts
  src/entities/index.ts
  src/paddle.ts
  src/resources/customer-portal-sessions/index.ts
  src/resources/customer-portal-sessions/operations/create-customer-portal-session-request-object.ts
  src/resources/customer-portal-sessions/operations/index.ts
  src/resources/index.ts
  src/types/customer-portal-session/customer-portal-session-response.ts
  src/types/customer-portal-session/customer-portal-subscription-url.ts
  src/types/customer-portal-session/general.ts
  src/types/customer-portal-session/index.ts
  src/types/customer-portal-session/urls.ts
  src/types/index.ts
Labels: release:minor

#77 fix: update customer portal sessions imports
  CHANGELOG.md
  package.json
  src/resources/customer-portal-sessions/index.ts
Labels: release:patch

#82 chore: add eslint file extension rule
  .eslintrc.yml
  CHANGELOG.md
  package.json
  src/resources/payment-methods/index.ts
Labels: release:patch
